# -*- coding: utf-8 -*-
"""smartwaste

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14a-OKD2NRH4fiWW0OfvQzXl9FpHNrHI-
"""



import os
os.environ["GEMINI_API_KEY"] = ""

import streamlit as st
import os
import google.generativeai as genai

# =========================
#   إعدادات Gemini
# =========================
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")

gemini_model = None
gemini_configured = False
gemini_error = ""

if GEMINI_API_KEY:
    try:
        genai.configure(api_key=GEMINI_API_KEY)
        gemini_model = genai.GenerativeModel("gemini-2.5-flash")
        gemini_configured = True
    except Exception as e:
        gemini_error = str(e)
else:
    gemini_error = "❌ لم يتم العثور على مفتاح GEMINI_API_KEY في المتغيرات البيئية."


# =========================
#   إعداد الصفحة
# =========================
st.set_page_config(
    page_title="SmartWaste",
    page_icon="♻️",
    layout="wide"
)

# =========================
#   التصميم
# =========================
st.markdown("""
    <style>
    .main-title {
        font-size: 3rem;
        font-weight: 800;
        text-align: center;
        margin-bottom: 0.3rem;
    }
    .subtitle {
        font-size: 1.2rem;
        text-align: center;
        color: #d0d0d0;
        margin-bottom: 2rem;
    }
    .hero {
        border-radius: 20px;
        padding: 2rem;
        background: linear-gradient(135deg, #1b5e20, #004d40);
        color: white;
        text-align: center;
        margin-bottom: 1.5rem;
    }
    .section-title {
        font-size: 1.8rem;
        font-weight: 700;
        color: #00c853;
        margin-top: 1.5rem;
        margin-bottom: 1rem;
    }
    </style>
""", unsafe_allow_html=True)


# =========================
#   القائمة الجانبية
# =========================
st.sidebar.title("♻️ SmartWaste")
page = st.sidebar.radio(
    "اختر صفحة:",
    ["الصفحة الرئيسية", "تشاتبوت إعادة التدوير"]
)


# =========================
#   الصفحة الرئيسية
# =========================
if page == "الصفحة الرئيسية":
    st.markdown('<div class="hero">', unsafe_allow_html=True)
    st.markdown('<div class="main-title">مرحبًا بك في SmartWaste</div>', unsafe_allow_html=True)
    st.markdown(
        '<div class="subtitle">تطبيق ذكي يقدم لك معلومات حول إعادة التدوير وتقليل النفايات.</div>',
        unsafe_allow_html=True
    )
    st.markdown("</div>", unsafe_allow_html=True)


# =========================
#   PAGE – CHATBOT
# =========================
elif page == "تشاتبوت إعادة التدوير":
    st.markdown('<div class="section-title">💬 تشاتبوت إعادة التدوير</div>', unsafe_allow_html=True)

    if not gemini_configured:
        st.error("❌ Gemini غير مفعّل.")
        st.code(gemini_error)
    else:
        user_q = st.text_input("اكتب سؤالك هنا:")

        if st.button("إرسال"):
            prompt = (
                "أنت مساعد متخصص في إعادة التدوير.\n"
                "أجب بإيجاز وبشكل واضح.\n\n"
                f"سؤال المستخدم: {user_q}"
            )
            try:
                response = gemini_model.generate_content(prompt)
                st.success("إجابة النموذج:")
                st.write(response.text)
            except Exception as e:
                st.error("حدث خطأ أثناء الاتصال بـ Gemini.")
                st.code(str(e))


